version: '3'
services:
    journal:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        ports:
            - "60000:80"
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: journal
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASWORD: root_password
            MYSQL_ALLOW_EMPTY_PASSWORD: empty_password
            MYSQL_RANDOM_ROOT_PASSWORD: random_password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
networks:
    app-network:
        driver: bridge
